[build]
  command = "npm install"  # Adjust this to your build script
  functions = "functions"  # Folder where serverless functions are stored
  publish = "dist"       # Adjust this to your build output directory
  memory = 10240


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
